### ISSUE TITLE
dlopen failed: library "libomp.so" not found

### ISSUE THREAD

**Issue by zia-shaadoow** [voxeet/voxeet-sdk-android-audio#2]
hi there,
i download this project and try to compile but than i got this issue dlopen failed: library "libomp.so" not found 
Can you guide me how i can fix this. i try to google but did not understand the issue. thanks

**Comment by sxj731533730** [comment]
cmakelist.txt 添加了
  find_library(android-lib android)

target_link_libraries( # Specifies the target library.
        native-lib
        jnigraphics
        libopencv_java4 # 链接opencv的so
        libncnn #链接ncnn静态的.a
        # Links the target library to the log library
        # included in the NDK.
        ${log-lib}
        ${android-lib}
        )

**Comment by CharyPro** [comment]
在CMakeLists.txt中添加类似下面相关配置
```
# openmp
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fopenmp")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fopenmp")
set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -fopenmp")

if(DEFINED ANDROID_NDK_MAJOR AND ${ANDROID_NDK_MAJOR} GREATER 20)
    set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -static-openmp")
endif()
```

**Comment by codlab** [comment]
This must have been an issue related to an incompatible ndk package installed on the machine. The current v2.2.0 branch is introducing the use of an upgraded Gradle environment + a specific ndkVersion set for the project to use side by side ndk

**Comment by lyqaiym** [comment]
cppFlags "-static-openmp"

**Comment by yangjian1218** [comment]
我也遇到过,如果添加的动态库全是小写,就会出现这种情况
